name: eldernet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - h5py
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
    - tensorboard
    - transforms3d
    - hydra-core
    - omegaconf